AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  atm-service

  SAM Template for atm-service

Parameters:
  LambdaAliasProduction:
    Type: String
    Description: Environment alias
  LambdaAliasBeta:
    Type: String
    Description: Environment alias

    ######################### Technical Parameters ############################
  DatabaseSecretArn:
    Type: String
    Description: "Arn del secreto que contiene los datos de conexion."
  EncryptionKeySecretName:
    Type: String
    Description: "Nombre del secreto de la llava de encriptación"
  EcsTaskExecutionRole:
    Type: String
    Description: "Rol de ejecución de tareas de AWS Batch"
  AWSBatchServiceRole:
    Type: String
    Description: "Rol de servicio de tareas de AWS Batch"
  SecurityGroupIds:
    Type: String
    Description: "Id de la VPC Endpoint que será asociada al API, esta solo se aplica si el API es de tipo privado."
  SubnetIds:
    Type: CommaDelimitedList
    Description: "Identificador de las subnets donde se desplegará el API de desarrollo (Deben estar entre comillas dobles y separadas por comas)."
  DbTarget:
    Type: String
    Description: "Instancia a la que se conectara el lambda master o replica"
  AwsAccountIdToDeploy:
    Type: String
    Description: Identificador de la cuenta AWS donde se desplegará el API de desarrollo.
  RegionToDeploy:
    Type: String
    AllowedValues: [us-east-2, us-west-2, us-east-1]
    ConstraintDescription: must specify us-east-2, us-west-2, us-east-1.
    Description: Región en la cual se realizará el despliegue del ambiente de desarrollo.
  LogLevel:
    Type: String
    AllowedValues: [INFO, DEBUG, WARNING, TRACE]
    ConstraintDescription: must specify INFO, DEBUG, WARNING or TRACE.
    Description: "Nivel de escritura de logs en los lambda INFO,DEBUG,WARNING,TRACE"
  LambdaAuthorizer:
    Type: String
    Description: "Nombre de la función lambda de tipo autorizador para el ambiente de desarrollo."
  DBConnectionExpirationTime:
    Type: Number
    Description: "Tiempo de reconexión a la base de datos."
  UserPoolId:
    Type: String
    Description: "Indica el user poolid para los token de autenticación."
  DaysRetention:
    Type: Number
  ImageBatchSharedResourcesAccount:
    Description: Imagen de ejecución procesos Batch de la cuenta de recursos compartidos
    Type: String
  StageMainVersionName:
    Description: Nombre de la version principal del stage del APIGateway
    Type: String
  ValueApiKey:
    Type: String
    MinLength: 20
    Description: "Valor del apikey."
  ExtDemandDeposits:
    Type: String
    Description: "Endpoint al Executor de Demand Deposits."
  ExtDemandDepositsApiKey:
    Type: String
    Description: "Api Key del Api Generico Demand Deposits."
  MainDomain:
      Type: String
      Description: "Dominios propios del Modulo."
      Default: "atm,atm_cp,general,channels"
  AtmExecutorLambdaConfiguration:
    Description: "AtmExecutorLambda"
    Type: String
    Default: "1024:0:0:0:0:0:INFO"
  AtmFileProcessingLambdaConfiguration:
    Description: "AtmBatchUpdatingLambda"
    Type: String
    Default: "1024:0:0:0:0:0:INFO"
  TransferFamilyUserIn:
    Description: "Nombre de usuario de conexión al SFTP en el directorio de entrada"
    Type: String
  TransferFamilyServerId:
    Description: "Instancia del servidor de transfer family que se encuentra ejecutando"
    Type: String
  TransferFamilyUserPublicKey:
    Description: "Llave publica que se utiliza para la autenticación de usuario"
    Type: String
    Default: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCMPnN4Z6p0CkF4WQKS+ksOpkrJOwvkef3oW+RzdnuezCS4al5uMHfLpF1mqnyGoy/LcPHqEfua/P5Gh+MiCbC7GwkEe9wnx8026XtxAeKwD7kyvncfc7dQ56O5feKhenhtoomEJMvY70i7qHagOXfjcgc8AQfi8N0EiOh8RUJWBLbX8gG/3CBQ7R+AIQAVdfDhG16t6AGz4hyyGEM/acClM8R7Sdxuzj9oFszN3JGx2PYfg2nZ+OnLygEBO3dsxLq1bpgQWpuwZ3vVmIurolziezeiiOqiqzEQbYSRgI3FnqH0HPTh4CUsuM+skCNTCmtoFnpxBo1WcnJd2VSc5xwp rsa-key-20220518"
  ###############################################
  #
  #   End - Tags  Configurations
  #
  ###############################################
  Organization:
    Type: String
    Description: "Identificador del dueño componente."
  Package:
    Type: String
    Description: "Identificador del paquete de productos comerciales al que se asocia el componente."
    Default: "COBIS CORE BANKING"
  Project:
    Type: String
    Description: "Identificador del proyecto por el que se crea el componente."
    Default: "Core Serverless"
  TenantId:
    Type: String
    Description: "Identificador del tenant."
  EnvironmentId:
    Type: String
    Description: "Identificador del ambiente."
  EnvironmentIdBase:
    Type: String
    Description: "Prefijo de recursos de la infraestructura base para referenciar en el microservicio.Pueden ser [dev,stg,prod o otro personalizado]"
  EnvironmentType:
    Type: String
    AllowedValues: [Production, Staging, Quality, Development, Integration, Formation, Migration]
    ConstraintDescription: must specify Production, Staging, Quality, Development, Integration, Formation, Migration.
  Module:
    Type: String
    Description: "Identificador del módulo."
    Default: "Atm"
  ModuleNameInLowerCase:
    Type: String
    Description: "Nombre del módulo o microservicio en minusculas."
    Default: "atm"
  Version:
    Type: String
    Description: "Versión del módulo o aplicación a la que pertenece el componente."
  TimeZone:
    Type: String
    Description: "Indica la zona horaria que tomara el servicio."
    Default: "America/Bogota"
  ProcessingType:
    Type: String
    Description: "Tipo de procesamiento."
  LoggingBucket:
    Default: ""
    Type: String
    Description: "Bucket en el cual se almacenaran los logs de acceso a s3"       
  ###############################################
  #
  #   End - Tags  Configurations
  #
  ###############################################

Conditions:
  StageQA: !Equals [!Ref EnvironmentType, STAGING]
  StageProd: !Equals [!Ref EnvironmentType, PRODUCTION]
  StageDev: !Equals [!Ref EnvironmentType, DEVELOPMENT]
  retentionEnvQACondition: !Equals [!Ref EnvironmentType, STAGING]
  retentionEnvProdCondition: !Equals [!Ref EnvironmentType, PRODUCTION]

Resources:
  TagResourceGroups:
    Type: "AWS::ResourceGroups::Group"
    Properties:
      Name: !Join
        - ""
        - - !Ref EnvironmentId
          - "-"
          - !Ref Module
      Description: "Grupo de recursos del modulo de Atm."
      ResourceQuery:
        Type:
          "TAG_FILTERS_1_0" 
        Query:
          ResourceTypeFilters: 
            - "AWS::AllSupported" 
          TagFilters:
            - 
              Key: "MODULE" 
              Values: 
                - !Ref Module
            - 
              Key: "ENVIRONMENT_ID" 
              Values: 
                - !Ref EnvironmentId

  LambdasInfrastructure:
    Type: AWS::Serverless::Application
    Properties:
      Location: cobis-atm-online/online-compute-template.yaml
      Parameters:
        LambdaAliasProduction: !Ref LambdaAliasProduction
        LambdaAliasBeta: !Ref LambdaAliasBeta
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Join
          - ","
          - !Ref SubnetIds
        DbTarget: !Ref DbTarget
        AwsAccountIdToDeploy: !Ref AwsAccountIdToDeploy
        RegionToDeploy: !Ref RegionToDeploy
        LogLevel: !Ref LogLevel
        LambdaAuthorizer: !Ref LambdaAuthorizer
        DatabaseSecretArn: !Ref DatabaseSecretArn
        EncryptionKeySecretName: !Ref EncryptionKeySecretName
        ExtDemandDeposits: !Ref ExtDemandDeposits
        ExtDemandDepositsApiKey: !Ref ExtDemandDepositsApiKey
        MainDomain: !Ref MainDomain
        DBConnectionExpirationTime: !Ref DBConnectionExpirationTime
        UserPoolId: !Ref UserPoolId
        TimeZone: !Ref TimeZone
        DaysRetention: !Ref DaysRetention
        Organization: !Ref Organization
        Package: !Ref Package
        Version: !Ref Version
        EnvironmentId: !Ref EnvironmentId
        EnvironmentIdBase: !Ref EnvironmentIdBase
        EnvironmentType: !Ref EnvironmentType
        TenantId: !Ref TenantId
        Project: !Ref Project
        Module: !Ref Module
        ProcessingType: !Ref ProcessingType
        StageName: !If [StageDev, v1-beta, !Ref StageMainVersionName]
        StageMainVersionName: !Ref StageMainVersionName
        ValueApiKey: !Ref ValueApiKey
        AtmExecutorLambdaConfiguration: !Ref AtmExecutorLambdaConfiguration
        ApiGatewayResponseMessage400: "El mensaje de solicitud no se encuentra debidamente formateado."
        ApiGatewayResponseMessage401: "No se encuentra autorizado para ejecutar la operación."
        ApiGatewayResponseMessage403: "La solicitud ha sido denegada."
        ApiGatewayResponseMessage404: "El objeto no fue encontrado."
        ApiGatewayResponseMessage405: "La operación (método, ej: GET, POST, etc.) que se trata de ejecutar no se encuentra soportado para el contexto."
        ApiGatewayResponseMessage409: "La operación presentó un error durante la ejecución."
        ApiGatewayResponseMessage429: "Se han realizado demasiadas solicitudes."
        ApiGatewayResponseMessage500: "Se presentó un error durante el procesamiento de la solicitud."
      Tags:
        ORGANIZATION: !Ref Organization
        PACKAGE: !Ref Package
        VERSION: !Ref Version
        ENVIRONMENT_TYPE: !Ref EnvironmentType
        ENVIRONMENT_ID: !Ref EnvironmentId
        TENANT_ID: !Ref TenantId
        PROJECT: !Ref Project
        MODULE: !Ref Module
        PROCESSING_TYPE: !Ref ProcessingType


  BatchInfrastructure:
    Type: AWS::Serverless::Application
    Properties:
      Location: cobis-atm-batch/batch-compute-template.yaml
      Parameters:
        AwsAccountIdToDeploy: !Ref AwsAccountIdToDeploy
        RegionToDeploy: !Ref RegionToDeploy
        LogLevel: !Ref LogLevel
        Organization: !Ref Organization
        Package: !Ref Package
        Version: !Ref Version
        EnvironmentId: !Ref EnvironmentId
        EnvironmentIdBase: !Ref EnvironmentIdBase
        EnvironmentType: !Ref EnvironmentType
        TenantId: !Ref TenantId
        Project: !Ref Project
        Module: !Ref Module
        ProcessingType: !Ref ProcessingType
        SecurityGroupIds: !Ref SecurityGroupIds
        EcsTaskExecutionRole : !Ref EcsTaskExecutionRole
        AWSBatchServiceRole: !Ref AWSBatchServiceRole
        AtmFileProcessingLambdaConfiguration: !Ref AtmFileProcessingLambdaConfiguration
        ModuleNameInLowerCase: !Ref ModuleNameInLowerCase
        ImageBatchSharedResourcesAccount: !Ref ImageBatchSharedResourcesAccount
        DatabaseSecretArn: !Ref DatabaseSecretArn
        EncryptionKeySecretName: !Ref EncryptionKeySecretName
        TimeZone: !Ref TimeZone
        TransferFamilyUserIn: !Ref TransferFamilyUserIn
        TransferFamilyServerId: !Ref TransferFamilyServerId
        TransferFamilyUserPublicKey: !Ref TransferFamilyUserPublicKey
        SubnetIds: !Join
          - ","
          - !Ref SubnetIds
        LoggingBucket: !Ref LoggingBucket
      Tags:
        ORGANIZATION: !Ref Organization
        PACKAGE: !Ref Package
        VERSION: !Ref Version
        ENVIRONMENT_TYPE: !Ref EnvironmentType
        ENVIRONMENT_ID: !Ref EnvironmentId
        TENANT_ID: !Ref TenantId
        PROJECT: !Ref Project
        MODULE: !Ref Module
        PROCESSING_TYPE: !Ref ProcessingType

        
  AchCloudWatchQueryInsights:
    Type: AWS::Serverless::Application
    Properties:
      Location: template-query-insights.yaml
      Parameters:
        EnvironmentId: !Ref EnvironmentId
        Module: !Ref ModuleNameInLowerCase
      Tags:
        ORGANIZATION: !Ref Organization
        PACKAGE: !Ref Package
        VERSION: !Ref Version
        ENVIRONMENT_TYPE: !Ref EnvironmentType
        ENVIRONMENT_ID: !Ref EnvironmentId
        TENANT_ID: !Ref TenantId
        PROJECT: !Ref Project
        MODULE: !Ref Module
        PROCESSING_TYPE: !Ref ProcessingType