AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for Query Insights in ATM Service

Parameters:
  EnvironmentId:
    Type: String
    Description: "Identificador del ambiente."
  Module:
    Type: String
    Description: "Nombre del módulo o microservicio."
Resources:
  # ---------------- ATM Resources query insights -----------------------#
  AtmTransactionAllQueryDefinition:
    Type: AWS::Logs::QueryDefinition
    Properties:
      LogGroupNames:
        - !Sub "/aws/ecs/${EnvironmentId}-atm-cis"
      Name: !Join
        - ""
        - - !Ref EnvironmentId
          - !Sub "/${Module}/Transactions/all"
      QueryString: "fields @timestamp, @message | sort @timestamp asc | filter @message like '{P3-processingCode}' and @message like '{P2-primaryAccountNumber}' | limit 1000"
  AtmTransactionOneTransaccionQueryDefinition:
    Type: AWS::Logs::QueryDefinition
    Properties:
      LogGroupNames:
        - !Sub "/aws/ecs/${EnvironmentId}-atm-cis"
      Name: !Join
        - ""
        - - !Ref EnvironmentId
          - !Sub "/${Module}/Transactions/oneTransaccion"
      QueryString: "fields @timestamp, @message | sort @timestamp asc | filter @message like '{transactionReference}' | limit 1000"


  AtmTransactionCorrelateTcpHandlerQueryDefinition:
    Type: AWS::Logs::QueryDefinition
    Properties:
      LogGroupNames:
        - !Sub "/aws/ecs/${EnvironmentId}-atm-cis"
        - !Sub "/aws/ecs/${EnvironmentId}-tcphandler"
      Name: !Join
        - ""
        - - !Ref EnvironmentId
          - !Sub "/${Module}/Transactions/CorrelateTcpHandler"
      QueryString: "fields @timestamp, @message | sort @timestamp desc | filter @message like '{transactionReference}' | limit 1000"

