AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  atm-service

  SAM Template for atm-service lambda

Parameters:
  TimeZone:
    Type: String
    Description: "Identificador de zona horaria."
  LambdaAliasProduction:
    Type: String
    Description: Environment alias
  LambdaAliasBeta:
    Type: String
    Description: Environment alias
  ApiGatewayResponseMessage400:
    Type: String
    Description: message error 400
  ApiGatewayResponseMessage401:
    Type: String
    Description: message error 401
  ApiGatewayResponseMessage403:
    Type: String
    Description: message error 403
  ApiGatewayResponseMessage404:
    Type: String
    Description: message error 404
  ApiGatewayResponseMessage405:
    Type: String
    Description: message error 405
  ApiGatewayResponseMessage409:
    Type: String
    Description: message error 409
  ApiGatewayResponseMessage429:
    Type: String
    Description: message error 429
  ApiGatewayResponseMessage500:
    Type: String
    Description: message error 500
  DatabaseSecretArn:
    Type: String
    Description: "Arn del secreto que contiene los datos de conexion."
  SecurityGroupIds:
    Type: String
    Description: "Id de la VPC Endpoint que será asociada al API, esta solo se aplica si el API es de tipo privado."
  SubnetIds:
    Type: CommaDelimitedList
    Description: "Identificador de las subnets donde se desplegará el API de desarrollo (Deben estar entre comillas dobles y separadas por comas)."
  DbTarget:
    Type: String
    Description: "Instancia a la que se conectara el lambda replica"
  AwsAccountIdToDeploy:
    Type: String
    Description: Identificador de la cuentas AWS donde se desplegará el API de desarrollo.
  RegionToDeploy:
    Type: String
    AllowedValues: [us-east-2, us-west-2, us-east-1]
    ConstraintDescription: must specify us-east-2,us-west-2,us-east-1.
    Description: Región en la cual se realizará el despliegue del ambiente de desarrollo.
  LogLevel:
    Type: String
    AllowedValues: [INFO, DEBUG, WARNING, TRACE]
    ConstraintDescription: must specify INFO, DEBUG, WARNING or TRACE.
    Description: "Nivel de escritura de logs en los lambda INFO,DEBUG,WARNING,TRACE"
  LambdaAuthorizer:
    Type: String
    Description: "Nombre de la función lambda de tipo autorizador para el ambiente de desarrollo."
  DBConnectionExpirationTime:
    Type: Number
    Description: "Tiempo de reconexión a la base de datos."
  UserPoolId:
    Type: String
    Description: "Indica el user poolid para los token de autenticación."
  DaysRetention:
    Type: Number
  StageName:
    Type: String
    Description: "Indica el nombre del stage del API Gateway."
  StageMainVersionName:
    Description: Nombre de la version principal de el stage del APIGateway
    Type: String
  # More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
  ValueApiKey:
    Type: String
    MinLength: 20
    Description: "Valor del apikey."
  ExtDemandDeposits:
    Type: String
    Description: "Endpoint al Executor de Demand Deposits."
  ExtDemandDepositsApiKey:
    Type: String
    Description: "Api Key del Api Generico Demand Deposits."
    Default: "noused"
  MainDomain:
    Type: String
    Description: "Dominios propios del Modulo."
  AtmExecutorLambdaConfiguration:
    Description: "AtmExecutorLambda"
    Type: String
    Default: "1024:0:0:0:0:0:INFO"
  Organization:
    Type: String
    Description: "Identificador del dueño componente."
  Package:
    Type: String
    Description: "Identificador del paquete de productos comerciales al que se asocia el componente."
  Version:
    Type: String
    Default: "0.1"
    Description: "Versión del módulo o aplicación a la que pertenece el componente."
  EnvironmentId:
    Type: String
    Description: "Identificador del ambiente."
  EnvironmentIdBase:
    Type: String
    Description: "Prefijo de recursos de la infraestructura base para referenciar en el microservicio.Pueden ser [dev,stg,prod o otro personalizado]"
  EnvironmentType:
    Type: String
    AllowedValues: [Production, Staging, Quality, Development, Integration, Formation, Migration]
    ConstraintDescription: must specify Production, Staging, Quality, Development, Integration, Formation, Migration.
  TenantId:
    Type: String
    Description: "Identificador del tenant."
  Project:
    Type: String
    Description: "Identificador del proyecto por el que se crea el componente."
  Module:
    Type: String
    Description: "Identificador del módulo."
  ProcessingType:
    Type: String
    Description: "Tipo de procesamiento."
  EncryptionKeySecretName:
    Type: String
    Description: "Nombre del secreto donde esta la llave de cifrado"

Conditions:
  StageVersionAliasProd: !Equals [!Ref EnvironmentType, PRODUCTION]

Resources:

  AtmAutoScalingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: [ lambda.amazonaws.com ] }
            Action: [ 'sts:AssumeRole' ]
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub "${EnvironmentId}-policy_allows_autoscaling"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: [ 'lambda:PutProvisionedConcurrencyConfig','lambda:GetProvisionedConcurrencyConfig','cloudwatch:PutMetricAlarm' ]
                Resource: "arn:aws:lambda:*:*:function:*"
      Tags:
        - Key: "ORGANIZATION"
          Value: !Ref Organization
        - Key: "PACKAGE"
          Value: !Ref Package
        - Key: "VERSION"
          Value: !Ref Version
        - Key: "ENVIRONMENT_TYPE"
          Value: !Ref EnvironmentType
        - Key: "ENVIRONMENT_ID"
          Value: !Ref EnvironmentId
        - Key: "TENANT_ID"
          Value: !Ref TenantId
        - Key: "PROJECT"
          Value: !Ref Project
        - Key: "MODULE"
          Value: !Ref Module
        - Key: "PROCESSING_TYPE"
          Value: !Ref ProcessingType

  AtmLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Join
        - ""
        - - !Ref EnvironmentId
          - "-atm-layer"
      Description: Librerias base del módulo de atm
      ContentUri: dependencies/atm-layer
      CompatibleRuntimes:
        - java11
        - java8
        - java8.al2
      CompatibleArchitectures:
        - arm64
        - x86_64
      LicenseInfo: "MIT"
      RetentionPolicy: Retain

  AtmRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Join
        - ""
        - - !Ref EnvironmentId
          - "-AtmRole"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: !Sub "${EnvironmentId}-policy_allows_getsecretvalue"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Ref DatabaseSecretArn
        - PolicyName: !Sub "${EnvironmentId}-policy_dynamodb_messaging"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:BatchGet*'
                  - 'dynamodb:Get*'
                  - 'dynamodb:Query'
                  - 'dynamodb:Scan'
                  - 'dynamodb:Update*'
                  - 'dynamodb:PutItem'                  
                Resource: !Sub "arn:aws:dynamodb:*:*:table/${EnvironmentId}-fe-messaging"

        - PolicyName: !Sub "${EnvironmentId}-atm-policy_allow_getSecretValue"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'secretsmanager:GetSecretValue'
                Resource: 'arn:aws:secretsmanager:*:*:secret:*'
      Tags:
        - Key: "ORGANIZATION"
          Value: !Ref Organization
        - Key: "PACKAGE"
          Value: !Ref Package
        - Key: "VERSION"
          Value: !Ref Version
        - Key: "ENVIRONMENT_TYPE"
          Value: !Ref EnvironmentType
        - Key: "ENVIRONMENT_ID"
          Value: !Ref EnvironmentId
        - Key: "TENANT_ID"
          Value: !Ref TenantId
        - Key: "PROJECT"
          Value: !Ref Project
        - Key: "MODULE"
          Value: !Ref Module
        - Key: "PROCESSING_TYPE"
          Value: !Ref ProcessingType
 
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess"
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
        - "arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess"
 
  AtmMonitoringPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: AtmMonitoringPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: "lambda:InvokeFunction"
            #Resource: '*'
            # Validacion Seguridad
            Resource:
              - "arn:aws:lambda:*:*:function:*"
          - Effect: Allow
            #Action: 'events:*'
            # Validacion seguridad
            Action:
              - "events:PutTargets"
            #Resource: '*'
            # Validacion Seguridad
            Resource:
              - "arn:aws:events:*:*:*"
          - Effect: Allow
            Action:
              - "events:PutRule"
            #Resource: '*'
            # Validacion Seguridad
            Resource:
              - "arn:aws:events:*:*:*"
              
          - Effect: Allow
            Action:
              - "events:DescribeRule"
            #Resource: '*'
            # Validacion Seguridad
            Resource:
              - "arn:aws:events:*:*:*"          
          - Effect: Allow
            Action:
              - "events:PutEvents"
            #Resource: '*'
            # Validacion Seguridad
            Resource:
              - "arn:aws:events:*:*:*"                       
          - Effect: Allow
            Action:
              - "events:ListRules"
            #Resource: '*'
            # Validacion Seguridad
            Resource:
              - "arn:aws:events:*:*:*"           
          - Effect: Allow
            Action:
              - "events:CreateEventBus"
            #Resource: '*'
            # Validacion Seguridad
            Resource:
              - "arn:aws:events:*:*:*"            
          - Effect: Allow
            Action:
              - "events:DescribeEventBus"
            #Resource: '*'
            # Validacion Seguridad
            Resource:
              - "arn:aws:events:*:*:*"
      Roles:
        - !Ref AtmRole
    #----------------------------------------

  ExecutorLambdas:
    Type: AWS::Serverless::Application
    Properties:
      Location: online-compute-executor-template.yaml
      Parameters:
        LambdaAliasProduction: !Ref LambdaAliasProduction
        LambdaAliasBeta: !Ref LambdaAliasBeta
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Join
          - ","
          - !Ref SubnetIds
        DbTarget: !Ref DbTarget
        AwsAccountIdToDeploy: !Ref AwsAccountIdToDeploy
        RegionToDeploy: !Ref RegionToDeploy
        LogLevel: !Ref LogLevel
        LambdaAuthorizer: !Ref LambdaAuthorizer
        DatabaseSecretArn: !Ref DatabaseSecretArn
        ExtDemandDeposits: !Ref ExtDemandDeposits
        ExtDemandDepositsApiKey: !Ref ExtDemandDepositsApiKey
        MainDomain: !Ref MainDomain
        DBConnectionExpirationTime: !Ref DBConnectionExpirationTime
        UserPoolId: !Ref UserPoolId
        TimeZone: !Ref TimeZone
        EncryptionKeySecretName: !Ref EncryptionKeySecretName
        DaysRetention: !Ref DaysRetention
        Organization: !Ref Organization
        Package: !Ref Package
        Version: !Ref Version
        EnvironmentId: !Ref EnvironmentId
        EnvironmentIdBase: !Ref EnvironmentIdBase
        EnvironmentType: !Ref EnvironmentType
        TenantId: !Ref TenantId
        Project: !Ref Project
        Module: !Ref Module
        ProcessingType: !Ref ProcessingType
        StageName: !Ref StageName
        StageMainVersionName: !Ref StageMainVersionName
        ValueApiKey: !Ref ValueApiKey
        AtmRoleArn: !GetAtt "AtmRole.Arn"
        AtmLayer: !Ref AtmLayer
        AtmAutoScalingRole: !GetAtt "AtmAutoScalingRole.Arn"
        AtmExecutorLambdaConfiguration: !Ref AtmExecutorLambdaConfiguration
        ApiGatewayResponseMessage400: !Ref ApiGatewayResponseMessage400
        ApiGatewayResponseMessage401: !Ref ApiGatewayResponseMessage401
        ApiGatewayResponseMessage403: !Ref ApiGatewayResponseMessage403
        ApiGatewayResponseMessage404: !Ref ApiGatewayResponseMessage404
        ApiGatewayResponseMessage405: !Ref ApiGatewayResponseMessage405
        ApiGatewayResponseMessage409: !Ref ApiGatewayResponseMessage409
        ApiGatewayResponseMessage429: !Ref ApiGatewayResponseMessage429
        ApiGatewayResponseMessage500: !Ref ApiGatewayResponseMessage500
      Tags:
        ORGANIZATION: !Ref Organization
        PACKAGE: !Ref Package
        VERSION: !Ref Version
        ENVIRONMENT_TYPE: !Ref EnvironmentType
        ENVIRONMENT_ID: !Ref EnvironmentId
        TENANT_ID: !Ref TenantId
        PROJECT: !Ref Project
        MODULE: !Ref Module
        PROCESSING_TYPE: !Ref ProcessingType